// <auto-generated />
namespace CarCounter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updatedsensormodelagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatedsensormodelagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201705100835091_Updated sensor model again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
